### ISSUE TITLE
does InsertBeforeAndRetargetOffsets() work as intended?

### ISSUE THREAD

**Issue by sanikolov** [microsoft/CLRInstrumentationEngine#179]
In the example below the program to be instrumented begins with a nop instruction.
I attempt the simplest usage of InsertBeforeAndRetargetOffsets that I can think of - insert a nop before the nop. Upon running the code the call never returns and CPU usage goes high and stays high. The following search returned nothing (no test cases for InsertBefore):
```
[lssw:/mnt/c/tmp/CLRInstrumentationEngine] git grep -i InsertBefore '*.xml'
```

Snippet follows
```
static std::vector<BYTE> EmitIL(CComPtr<IInstructionGraph> &igraph, bool retarget)
{
    if (retarget) {
        CComPtr<IInstruction> first;
        igraph->GetFirstInstruction(&first);
        igraph->InsertBeforeAndRetargetOffsets(first, first);
    // snipped here
}
```

Am I doing something wrong?
Are there any guidelines, gotchas, best practices w.r.t. InsertBeforeAndRetargetOffsets that users should be aware of?

**Comment by sanikolov** [comment]
Apparently, we are not supposed to be calling EmitIL ourselves. It suffices to alter the instruction graph, per an email exchange with clrieowners@microsoft.com .
However, the instruction graph alteration which is enacted by CreateBaseline, e.g.
**pInstructionGraph->CreateBaseline(ilCode.data(), ilCode.data() + ilCode.size(), (DWORD)corIlMap.size(), corIlMap.data(), (DWORD)baselineSequencePoints.size(), baselineSequencePoints.data())**

seems to be bytestream oriented, as shown above.
Note ilCode.data() and ilCode.data() + ilCode.size().
There is something I am still missing here.

**Comment by delmyers** [comment]
@sanikolov 

You should almost never need to use CreateBaseline. Most InstrumentationMethods will just edit the IL that comes from the method being jitted, which comes from the assembly file.  You can just edit the graph directly.

CreateBaseline is only used in cases where a single instrumentation method needs to replace the entire method body whole-sale, up-front. That is almost never necessary, and it shouldn't really be used by most instrumentation methods.

We should maybe make the documentation about this more clear.

**Comment by sanikolov** [comment]
Thanks for this explanation.
Since there is nothing to it other than editing the graph, I tried that but it's not working for me.
Below I am trying to replace the destination Main() C# class method with another similar static method which I call source.
Replacement manages to transfer 2 instructions and when program runs I get a crash.
In other words, InsertAfter, InsertBefore* are working in non intuitive ways.
Here is an example
```
 static std::vector<CComPtr<IInstruction>> getAllInstructions(CComPtr<IInstructionGraph> graph)
    {
        std::vector<CComPtr<IInstruction>> vec;
        CComPtr<IInstruction> first;
        graph->GetFirstInstruction(&first);
        auto instr = first;
        while (instr != nullptr) {
            vec.push_back(instr);
            CComPtr<IInstruction> next;
            instr->GetNextInstruction(&next);
            instr = next;
        }
        return vec;
    }
```

and the actual replacement below
```
static void replace_graph(CComPtr<IInstructionGraph> &dest, CComPtr<IInstructionGraph> &source)
    {
        auto src_vec = getAllInstructions(source); // C# method 1 - prints "hello world", that's all
        auto dst_vec = getAllInstructions(dest);   // C# method 2 - prints "abc 123", that's all
        // remove all instructions in dest except the last one
        for (long i = 0; i < (long) dst_vec.size() - 1; i++) dest->Remove(dst_vec[i]);
        // only ret remains in dest        
        src_vec.pop_back(); // exclude the last instruction (ret) from source
        // insert instructions from src_vec into dest backwards from last to first
        CComPtr<IInstruction> origInstr;
        dest->GetLastInstruction(&origInstr); // should be ret
        for (long i = (long) src_vec.size() - 1; i >= 0; i--)
        {
            auto newInstr = src_vec[i];
            dest->InsertBeforeAndRetargetOffsets(origInstr, newInstr);
            origInstr = newInstr;
        }
    }
```

**Comment by delmyers** [comment]
@sanikolov

Hmm... Attempting to take instructions from one graph, and place them into another is not something that we really support, and is probably something that we should guard against. When you insert instructions into a graph, the links in the graph have to be updated. I would have to look back into our code to see if there are any adverse effects in the original "source" graph.

Apart from that, where is your source graph coming from? Based on your previous questions, I'm guessing that you are loading an assembly into memory using LoadLibrary(), and then using IInstructionFactory::DecodeInstructionByteStream to get the graph.

If that is the case, then the most likely reason that your app is crashing is because your source byte stream is relative to the source module, not relative to the destination module. That is, the IL code will have tokens (types, strings, etc) in it that reference types that the source module knows about, but that the destination module does not. Or the destination module may reference the same types, but will have different token representations for those types.

A simple example is your string "abc 123". In the il stream of your original method, that string will not be encoded into the method. Instead, it will be assigned a "token" which is just an index into a string table in your source module. But, your destination module does not have the string "abc 123" in it, so the token will be meaningless, or will point to a bogus location in the destination module, which could easily cause a crash.

Another example is that your IL stream will likely reference the System.Console class and the System.Console.WriteLine method. These will both be represented by tokens in the IL stream, but those tokens will be relative to the source module. They will either represent nothing, or represent the wrong type and method when presented relative to the destination module.

If you want to copy IL from one module to another, then you have to do the work of normalizing all of the references and making them relative to the destination module. If one of the references is not valid in the destination module, then you have to create it in the destination module.

All of this is easier said than done, though. Tokens are used all over MSIL, including in method and type signatures. Redirecting them is pretty difficult and error prone. For that reason, we often just write our new IL code algorithmically from scratch, rather than trying to copy it from somewhere else.

**Comment by sanikolov** [comment]
I was trying to implement this https://www.codeproject.com/Articles/4567/The-Implementation-of-Model-Constraints-in-NET-II . In the article *public static int CCC:: __CheckMethodDefOnEnter* resides in an external DLL. What you wrote makes a lot of sense, yet what the author of the above article wrote implies that the external DLL (prolog/epilog) methods can be callable from instrumented code, and control passed to them without much trouble.
