### ISSUE TITLE
Every InsertBefore() calls CalculateInstructionOffsets() which can be quite slow

### ISSUE THREAD

**Issue by WilliamXieMSFT** [microsoft/CLRInstrumentationEngine#257]
Investigate where the bottleneck is in this call and if there can be performance improvements. Perhaps get a PerfTrace for PerfView

**Comment by jakubch1** [comment]
I did some tests on Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests project (roslyn). Example of  results:
No cc: 00:00:21.4588922
Coverlet: 00:01:57.4380399
Dynamic Intellitrace: 00:00:56.5028991
Dynamic CLR IE: 00:01:55.2505802

**Comment by delmyers** [comment]
I took a look at the perf trace supplied by @jakubch1 and it looks like most of the time here is spent logging messages:

|Name                                                                                                                        	|Exc %	 |Exc	|Inc %	  |Inc	  |
|-----------------------------------------------------------------------------------------------------------------------------|:------:|:----:|:-------:|:-----:|
|microsoftinstrumentationengine_x64!MicrosoftInstrumentationEngine::CProfilerManager::JITCompilationStarted                  	|  0.2	 | 36	| 95.9	  | 18,097|
|microsoftinstrumentationengine_x64!MicrosoftInstrumentationEngine::CProfilerManager::CallInstrumentOnInstrumentationMethods 	|  0.8	 |142	| 91.5	  | 17,252|
|microsoftinstrumentationengine_x64!MicrosoftInstrumentationEngine::CLogging::LogMessage                                     	|  0.3	 |55	| *90.8*	  | 17,126|
|microsoftinstrumentationengine_x64!MicrosoftInstrumentationEngine::CLoggerService::LogMessage                               	|  0.3	 |58	| *90.5*	  | 17,071|

**Comment by delmyers** [comment]
Following up on this, looks like even with logging off, we are spending a lot of time in the logging code, trying to get the logging flags. It's probably due to the critical section here:

https://github.com/microsoft/CLRInstrumentationEngine/blob/cad5ad3c6c12310e8f8cf135b1835aa877188205/src/InstrumentationEngine.Lib/LoggerService.cpp#L60

We should start by getting rid of that critical section (use an atomic integer instead to store it). If that doesn't get the inclusive time of the CLogging::LogMessage call to < 1%, then we should consider caching the logging flags inside CLogging, and supplying a callback for when the logging flags are updated so that we don't have to do the additional standard call, since the std calling convention needs to push/pop more registers. That could shave some additional time off.
