### ISSUE TITLE
Late binding using AddInstrumentationMethod 

### ISSUE THREAD

**Issue by robertpi** [microsoft/CLRInstrumentationEngine#342]
Hello all,

The [docs suggest](https://github.com/microsoft/CLRInstrumentationEngine/blob/develop/DESIGN-NOTES.md#components) that it's possible to use `AddInstrumentationMethod` to late bind an Instrumentation Method. I would like to do this, mainly to avoid the need for any kind of XML for the Instrumentation Method.

However, trying to do this I hit a sort of chicken and egg problem. I see `AddInstrumentationMethod` is on the `IProfilerManager`, but the only way to get a reference to this seams to be by going through the `Initialize` or `InitializeForAttach` of any existing. Instrumentation Method.

Is there anyway of getting a reference to `IProfilerManager` before any Instrumentation Method are created? I thought about using the DllGetClassObject method, but this looks like it would create an new `IProfilerManager`, I don't think this is what I want.

Many thanks,
Robert

**Comment by delmyers** [comment]
You can attach an instrumentation method to an already running process via profiler attach. The feature is only available in core clr 3+, however, and there are limitations. @jander-msft might be able to give you more info.

**Comment by WilliamXieMSFT** [comment]
Here's the project path for the Profiler Attach trigger process: https://github.com/microsoft/CLRInstrumentationEngine/tree/develop/src/InstrumentationEngine.Attach

CLRIE Configuration schema: https://github.com/microsoft/CLRInstrumentationEngine/blob/develop/src/InstrumentationEngine.Attach/EngineConfiguration.xsd

InstrumentationMethod Configuration schema: https://github.com/microsoft/CLRInstrumentationEngine/blob/develop/src/InstrumentationEngine.Attach/InstrumentationConfigurationSources.xsd

**Comment by robertpi** [comment]
Yes, it's pretty easy to attach the profiler, I can already do that. What I'd like to do is tell the profiler to dynamically load an Instrumentation Method once attached. Rather than having to specific my IM's config in an XML blob. Is that possible?

**Comment by delmyers** [comment]
@robertpi I think I'm a little confused about your use case. Are you trying to attach a profiler to an already running process, or do you want to add additional instrumentation methods to a process that you are already attached to?

My confusion arises because you indicate that you are already using the instrumentation method configuration file to attach an instrumentation method when the process starts. Do you want to do something else? Sorry if I'm being a little dense, but some more specific information might allow us to help you more effectively.

**Comment by robertpi** [comment]
I'm trying to port an profiler that wrote that used the old `ICorProfilerCallback` to be an `IInstrumentationMethod`.

One of the feature I support in my older profiler attaching to running process, so I already understand how that works. I've already implemented attaching the profiler, by that I mean the Instrumentation Engine multiplexing profiler, to a running process, by following example that @WilliamXieMSFT pointed to earlier.

To get my instrumentation method to load into the multiplexing profiler, I send an XML blob as part of the attach process. That xml blob must point to an xml file stored on disk someone what describes my instrumentation method.

Although this works fine in my tests, I'm hoping to distribute this to a clients and so the XML config on disk feels a bit brittle. I'd like to avoid this if possible. The doc seem to suggest that dynamically loading a instrumentation method into the multiplexing profiler is possible, but the only way I can see to do this is from an instrumentation method that is already loaded.

Does what I'm trying to achieve make sense now?

**Comment by delmyers** [comment]
I think I understand what you are saying now.

So, unfortunately, right now the only way to attach to a running process is to use the method that you described. The reason is that there are some limitations in the way the CLR allows attach, and you can't change configuration after attaching. So, for example if IInstrumentationMethod-A attaches first, and sets certain configurations for the profiler, then IInstrumentationMethod-B attaches later, it will not be able to set configuration due to the fact that 'A' did it first. So, you have to attach all instrumentation methods using a single configuration up-front. We use xml configuration on disk for that because it is the most consistent facility available to us across operating systems. Other forms of IPC are more difficult to get right across platforms.

The way that we would normally enable this in a more user-friendly way is to supply a command-line interface that uses our pre-set XML file to initialize the attach.

We have had discussions about trying to enable a more incremental attach for multiple instrumentation engines at different times, but their functionality would be cut back. You may not be able to listen for exception callbacks, for example.

If you would like to start a discussion about a design to get this feature into the product, we would welcome it.

**Comment by robertpi** [comment]
Not allowing late loading of Instrumentation Methods seems a fair restrictions, but if that's the case, I would suggest the design notes docs are misleading, as they state: ["Alternative way of registering and unregistering of Instrumentation Methods is by calling the method AddInstrumentationMethod from the code. This allows late-binding scenarios when certain features are enabled and disabled from the code dynamically"](https://github.com/microsoft/CLRInstrumentationEngine/blob/develop/DESIGN-NOTES.md#components)

The thing I dislike about the current design is that the XML blob sent to the profiler contains a path to the an xml config for the instrumentation method, rather than the details of the instrumentation method itself. If you where going to change anything, it would be great to be able to specify the details of the profiler in the initial XML blob.

**Comment by robertpi** [comment]
Yes and yes. Updating the docs and folding the instrumentation method to be folded into the schema for the attach data would be great.

**Comment by delmyers** [comment]
I've added issues #344 and #345. Is that what you are looking for? If yes, then it is probably appropriate to close this discussion, and continue discussion on those issues if necessary. Does that sound good to you?

**Comment by robertpi** [comment]
Yep. That's what I would like to see.
